- platform: flux_led
  automatic_add: true
  devices:
    !secret masterbedroomaccent:
      name: Master Bedroom Accent

- platform: group
  name: Basement Lamps
  entities:
    - light.lamp_left
    - light.lamp_right
    - light.lamp_tall
